Track_number: L
balls_count: '8'
cardNo: '13'
color_ch:
  Brown: 棕 ⑩
  White: 白 ⑦
  black: 黑 ⑧
  blue: 蓝 ②
  green: 绿 ⑥
  orange: 橙 ⑨
  pink: 粉 ⑤
  purple: 紫 ④
  red: 红 ③
  yellow: 黄 ①
five_axis:
- -1
- 1
- 1
- 1
- 1
five_key:
- -1
- 1
- 1
- 1
- -1
init_array:
- - 0
  - 0
  - 0
  - 0
  - 0
  - yellow
  - 0
  - 0
  - 0
  - 0
- - 0
  - 0
  - 0
  - 0
  - 0
  - blue
  - 0
  - 0
  - 0
  - 0
- - 0
  - 0
  - 0
  - 0
  - 0
  - red
  - 0
  - 0
  - 0
  - 0
- - 0
  - 0
  - 0
  - 0
  - 0
  - purple
  - 0
  - 0
  - 0
  - 0
- - 0
  - 0
  - 0
  - 0
  - 0
  - pink
  - 0
  - 0
  - 0
  - 0
- - 0
  - 0
  - 0
  - 0
  - 0
  - green
  - 0
  - 0
  - 0
  - 0
- - 0
  - 0
  - 0
  - 0
  - 0
  - White
  - 0
  - 0
  - 0
  - 0
- - 0
  - 0
  - 0
  - 0
  - 0
  - black
  - 0
  - 0
  - 0
  - 0
- - 0
  - 0
  - 0
  - 0
  - 0
  - orange
  - 0
  - 0
  - 0
  - 0
- - 0
  - 0
  - 0
  - 0
  - 0
  - Brown
  - 0
  - 0
  - 0
  - 0
lineEdit_alarm: '10'
lineEdit_end: '5'
lineEdit_end1_Path: D:/数据/瀑布_终点/obs
lineEdit_end2_Path: D:/rtsp
lineEdit_saidao_Path: Z:/瀑布_赛道
lineEdit_shake: '11'
lineEdit_shoot: '1'
lineEdit_shoot_2: '2'
lineEdit_shoot_3: '4'
lineEdit_start: '3'
lineEdit_start_count: '13'
lineEdit_upload_Path: D:/数据/上报
map_line: ./img/12_瀑布.json
map_picture: ./img/12_瀑布.jpg
map_size: '680'
monitor_sort: '0'
music_1:
- false
- ./mp3/07_冰原背景音乐1.mp3
music_2:
- true
- ./mp3/07_冰原背景音乐2.mp3
music_3:
- false
- ./mp3/07_冰原背景音乐3.mp3
obs_script_addr: http://127.0.0.1:8899
pushButton_start_game: true
recognition_addr: http://127.0.0.1:6066
result_tcpServer_addr:
- 0.0.0.0
- '8888'
rtsp_url: rtsp://admin:123456@192.168.0.32:554/Streaming/Channels/101
s485_Axis_No: COM24
s485_Cam_No: COM20
scene_name: 现场
sony_sort: '1'
source_end: 终点1
source_picture: 画中画
source_ranking: 排名时间组件
source_settlement: 结算页
tcpServer_addr:
- 0.0.0.0
- '9999'
udpServer_addr:
- 0.0.0.0
- '19734'
wakeup_addr:
- http://192.168.0.113:8080
- http://192.168.0.127:8080
