cardNo: 10
plans:
  plan1:
    plan_list:
    - - '1'
      - '2'
      - '954050'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '300'
      - '0.3'
      - '0.2'
      - '-7'
      - '5'
      - '1'
      - '-1'
      - 0_现场
    - - '0'
      - '0'
      - '954050'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '200'
      - '0.3'
      - '0.2'
      - '3'
      - '3'
      - '-4'
      - '-1'
      - '0'
    - - '1'
      - '0'
      - '954050'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '-1'
      - '-1'
      - '0'
    - - '0'
      - '0'
      - '954050'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '2'
      - '2'
      - '0'
    - - '0'
      - '0'
      - '182116'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '3'
      - '0'
    - - '0'
      - '0'
      - '182116'
      - '1042316'
      - '0'
      - '-374366'
      - '190056'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '4'
      - '0'
    - - '0'
      - '0'
      - '579322'
      - '704985'
      - '0'
      - '-27776'
      - '190056'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '5'
      - '0'
    - - '0'
      - '0'
      - '908475'
      - '777918'
      - '0'
      - '185512'
      - '190056'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '6'
      - '0'
    - - '0'
      - '0'
      - '1179512'
      - '903180'
      - '0'
      - '319222'
      - '190056'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '9'
      - '0'
    - - '0'
      - '0'
      - '623366'
      - '469659'
      - '0'
      - '-50362'
      - '190056'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '13'
      - '0'
    - - '0'
      - '0'
      - '1504919'
      - '1285978'
      - '0'
      - '466294'
      - '414667'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '16'
      - '0'
    - - '0'
      - '0'
      - '1650318'
      - '580997'
      - '0'
      - '151033'
      - '327034'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '19'
      - '0'
    - - '0'
      - '0'
      - '1509424'
      - '685971'
      - '0'
      - '235058'
      - '327034'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '20'
      - '0'
    - - '0'
      - '0'
      - '1357556'
      - '842534'
      - '0'
      - '418492'
      - '581166'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '22'
      - '0'
    - - '0'
      - '0'
      - '1176133'
      - '1426892'
      - '0'
      - '819330'
      - '396752'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '25'
      - '0'
    - - '0'
      - '0'
      - '1121380'
      - '878358'
      - '0'
      - '562177'
      - '396752'
      - '400'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '26'
      - '0'
    - - '0'
      - '0'
      - '388940'
      - '1081676'
      - '0'
      - '1042836'
      - '538857'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '27'
      - '0'
    - - '0'
      - '0'
      - '144066'
      - '857432'
      - '0'
      - '1355799'
      - '538857'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '29'
      - '0'
    - - '0'
      - '0'
      - '649750'
      - '857432'
      - '0'
      - '1355799'
      - '538857'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '34'
      - '0'
    - - '0'
      - '0'
      - '677809'
      - '347908'
      - '0'
      - '1727169'
      - '694590'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '36'
      - '0'
    - - '0'
      - '0'
      - '736238'
      - '626222'
      - '0'
      - '1469782'
      - '528172'
      - '400'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '-2'
      - '38'
      - '0'
    - - '0'
      - '0'
      - '1334305'
      - '951262'
      - '0'
      - '992181'
      - '694590'
      - '150'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '4'
      - '39'
      - '0'
    - - '0'
      - '0'
      - '1523464'
      - '652534'
      - '892849'
      - '992181'
      - '734965'
      - '150'
      - '0.3'
      - '0.2'
      - '5'
      - '2'
      - '-1'
      - '-1'
      - 1_终点
    plan_name: 方案一
  plan2:
    plan_list:
    - - '0'
      - '2'
      - '3'
      - '4'
      - '5'
      - '6'
      - '7'
      - '8'
      - '9'
      - '10'
    plan_name: 方案二
  plan3:
    plan_list:
    - - '1'
      - '2'
      - '954050'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '300'
      - '0.3'
      - '0.2'
      - '-7'
      - '5'
      - '1'
      - '-1'
    - - '1'
      - '0'
      - '954050'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '-4'
      - '-1'
    - - '1'
      - '0'
      - '954050'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '-1'
      - '-1'
    - - '1'
      - '0'
      - '954050'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '2'
      - '2'
    - - '1'
      - '0'
      - '182116'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '3'
    - - '1'
      - '0'
      - '182116'
      - '1042316'
      - '0'
      - '-374366'
      - '190056'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '4'
    - - '1'
      - '0'
      - '579322'
      - '704985'
      - '0'
      - '-27776'
      - '190056'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '5'
    - - '1'
      - '0'
      - '908475'
      - '777918'
      - '0'
      - '185512'
      - '190056'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '6'
    - - '1'
      - '0'
      - '1179512'
      - '903180'
      - '0'
      - '319222'
      - '190056'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '9'
    - - '1'
      - '0'
      - '623366'
      - '469659'
      - '0'
      - '-50362'
      - '190056'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '13'
    - - '1'
      - '0'
      - '1504919'
      - '1285978'
      - '0'
      - '466294'
      - '414667'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '16'
      - 0_终点
    - - '1'
      - '0'
      - '1650318'
      - '580997'
      - '0'
      - '151033'
      - '327034'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '19'
    - - '1'
      - '0'
      - '1509424'
      - '685971'
      - '0'
      - '235058'
      - '327034'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '20'
    - - '1'
      - '0'
      - '1357556'
      - '842534'
      - '0'
      - '418492'
      - '581166'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '22'
    - - '1'
      - '0'
      - '1176133'
      - '1426892'
      - '0'
      - '819330'
      - '396752'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '24'
    - - '1'
      - '0'
      - '1121380'
      - '878358'
      - '0'
      - '562177'
      - '396752'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '26'
    - - '1'
      - '0'
      - '388940'
      - '1081676'
      - '0'
      - '1042836'
      - '538857'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '27'
    - - '1'
      - '0'
      - '144066'
      - '857432'
      - '0'
      - '1355799'
      - '538857'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '27'
    - - '1'
      - '0'
      - '649750'
      - '857432'
      - '0'
      - '1355799'
      - '538857'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '34'
    - - '1'
      - '0'
      - '677809'
      - '347908'
      - '0'
      - '1727169'
      - '694590'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '36'
    - - '1'
      - '0'
      - '736238'
      - '626222'
      - '0'
      - '1469782'
      - '528172'
      - '400'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '-2'
      - '38'
    - - '1'
      - '0'
      - '1334305'
      - '951262'
      - '0'
      - '992181'
      - '694590'
      - '150'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '4'
      - '39'
    - - '1'
      - '0'
      - '1523464'
      - '652534'
      - '892849'
      - '992181'
      - '734965'
      - '150'
      - '0.3'
      - '0.2'
      - '5'
      - '2'
      - '-1'
      - '-1'
    plan_name: 方案三
s485_Axis_No: COM23
s485_Cam_No: COM1
