plans:
  plan1:
    plan_list:
    - - '1'
      - '1'
      - '954050'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '-1'
      - '0'
      - '0'
      - 10_现场
    - - '1'
      - '1'
      - '954050'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '300'
      - '0.3'
      - '0.2'
      - '-7'
      - '5'
      - '1'
      - '-1'
      - '0'
      - '0'
      - 0_结算页
    - - '1'
      - '1'
      - '954050'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '5'
      - '-4'
      - '-1'
      - '0'
      - '0'
      - '0'
    - - '1'
      - '1'
      - '954050'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '5'
      - '11'
      - '-1'
      - '0'
      - '0'
      - '0'
    - - '1'
      - '1'
      - '954050'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '1'
      - '10'
      - '-1'
      - '0'
      - '0'
      - '0'
    - - '1'
      - '1'
      - '954050'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '4'
      - '5'
      - '-1'
      - '0'
      - '1'
      - '0'
    - - '1'
      - '1'
      - '954050'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '-1'
      - '-1'
      - '0'
      - '0'
      - '0'
    - - '1'
      - '1'
      - '954050'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '2'
      - '-1'
      - '0'
      - '0'
      - '0'
    - - '1'
      - '1'
      - '954050'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '3'
      - '-1'
      - '0'
      - '0'
      - '0'
    - - '1'
      - '3'
      - '330216'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '1'
      - '1'
      - '0'
      - '0'
    - - '1'
      - '3'
      - '206119'
      - '1274090'
      - '0'
      - '-374366'
      - '96763'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '3'
      - '2'
      - '0'
      - '0'
    - - '1'
      - '3'
      - '206119'
      - '974656'
      - '0'
      - '-374366'
      - '206178'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '4'
      - '3'
      - '0'
      - 0_画中画
    - - '1'
      - '3'
      - '204765'
      - '809722'
      - '0'
      - '-309732'
      - '206178'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '-3'
      - '5'
      - '4'
      - '0'
      - '0'
    - - '1'
      - '3'
      - '204765'
      - '671073'
      - '0'
      - '-240360'
      - '206178'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '6'
      - '5'
      - '0'
      - '0'
    - - '1'
      - '3'
      - '143483'
      - '671073'
      - '0'
      - '-270554'
      - '243353'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '11'
      - '6'
      - '0'
      - '0'
    - - '1'
      - '3'
      - '552800'
      - '561638'
      - '0'
      - '-90646'
      - '304592'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '14'
      - '7'
      - '0'
      - '0'
    - - '1'
      - '3'
      - '1444918'
      - '1030173'
      - '0'
      - '55208'
      - '583258'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '16'
      - '8'
      - '0'
      - '0'
    - - '1'
      - '3'
      - '1650318'
      - '467963'
      - '0'
      - '126006'
      - '327034'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '22'
      - '9'
      - '0'
      - '0'
    - - '1'
      - '3'
      - '1650318'
      - '240119'
      - '0'
      - '271551'
      - '327034'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '24'
      - '10'
      - '0'
      - '0'
    - - '1'
      - '3'
      - '1230921'
      - '532589'
      - '0'
      - '382535'
      - '327034'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '-1'
      - '25'
      - '11'
      - '0'
      - '0'
    - - '1'
      - '3'
      - '936947'
      - '902580'
      - '0'
      - '608626'
      - '535772'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '27'
      - '12'
      - '0'
      - '0'
    - - '1'
      - '3'
      - '1608900'
      - '730634'
      - '0'
      - '605659'
      - '596299'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '35'
      - '13'
      - '0'
      - '0'
    - - '1'
      - '3'
      - '1207626'
      - '1024433'
      - '0'
      - '917362'
      - '658017'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '1'
      - '36'
      - '14'
      - '0'
      - 1_画中画
    - - '1'
      - '3'
      - '1375159'
      - '1023799'
      - '0'
      - '812654'
      - '658017'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '37'
      - '15'
      - '0'
      - '0'
    - - '1'
      - '3'
      - '1690633'
      - '699575'
      - '0'
      - '549500'
      - '658017'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '38'
      - '16'
      - '0'
      - '0'
    - - '1'
      - '3'
      - '1690633'
      - '668184'
      - '0'
      - '549500'
      - '812007'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '-1'
      - '17'
      - '0'
      - '0'
    plan_name: 方案一
  plan2:
    plan_list:
    - - '0'
      - '2'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '1'
      - '-1'
      - 弹射
      - '0'
    - - '1'
      - '2'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '-1'
      - '-1'
      - '0'
      - '0'
    - - '0'
      - '2'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '2'
      - '-1'
      - 闸门
      - '0'
    - - '1'
      - '2'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '-2'
      - '-1'
      - '0'
      - '0'
    - - '0'
      - '2'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '3'
      - '-1'
      - 震动
      - '0'
    - - '1'
      - '2'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '-3'
      - '-1'
      - '0'
      - '0'
    - - '0'
      - '2'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '5'
      - '-1'
      - 高低桩
      - '0'
    - - '1'
      - '2'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '-5'
      - '-1'
      - '0'
      - '0'
    - - '0'
      - '2'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '6'
      - '-1'
      - '0'
      - '0'
    - - '1'
      - '2'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '-6'
      - '-1'
      - '0'
      - '0'
    - - '0'
      - '2'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '7'
      - '-1'
      - '0'
      - '0'
    - - '1'
      - '2'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '-7'
      - '-1'
      - '0'
      - '0'
    - - '0'
      - '2'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '8'
      - '-1'
      - '0'
      - '0'
    - - '0'
      - '2'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '-8'
      - '-1'
      - '0'
      - '0'
    - - '0'
      - '2'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '9'
      - '-1'
      - '0'
      - '0'
    - - '0'
      - '2'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '-9'
      - '-1'
      - 倒计时
      - '0'
    - - '0'
      - '2'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '10'
      - '-1'
      - 摆锤
      - '0'
    - - '0'
      - '2'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '-10'
      - '-1'
      - '0'
      - '0'
    - - '0'
      - '2'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '11'
      - '-1'
      - 指针
      - '0'
    - - '0'
      - '2'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '-11'
      - '-1'
      - '0'
      - '0'
    - - '0'
      - '2'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '4'
      - '-1'
      - 终点
      - '0'
    - - '1'
      - '2'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '-4'
      - '-1'
      - '0'
      - '0'
    plan_name: 方案二
  plan3:
    plan_list:
    - - '0'
      - '2'
      - '954050'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '300'
      - '0.3'
      - '0.2'
      - '-7'
      - '5'
      - '1'
      - '-1'
      - '0'
      - '0'
    - - '0'
      - '0'
      - '954050'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '5'
      - '-4'
      - '-1'
      - '0'
      - '0'
    - - '0'
      - '0'
      - '954050'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '5'
      - '11'
      - '-1'
      - '0'
      - '0'
    - - '0'
      - '0'
      - '954050'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '10'
      - '-1'
      - '0'
      - '0'
    - - '0'
      - '0'
      - '954050'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '5'
      - '5'
      - '-1'
      - '0'
      - '0'
    - - '0'
      - '0'
      - '954050'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '3'
      - '-1'
      - '0'
      - '0'
    - - '1'
      - '0'
      - '954050'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '2'
      - '-1'
      - '0'
      - '0'
    - - '0'
      - '0'
      - '330216'
      - '1460828'
      - '0'
      - '-374366'
      - '96763'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '1'
      - '-1'
      - '1'
      - '0'
      - '0'
    - - '0'
      - '0'
      - '206119'
      - '1274090'
      - '0'
      - '-374366'
      - '96763'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '-3'
      - '3'
      - '0'
      - '0'
    - - '0'
      - '0'
      - '206119'
      - '974656'
      - '0'
      - '-374366'
      - '206178'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '4'
      - '0'
      - '0'
    - - '0'
      - '0'
      - '204765'
      - '809722'
      - '0'
      - '-309732'
      - '206178'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '5'
      - '0'
      - '0'
    - - '0'
      - '0'
      - '204765'
      - '671073'
      - '0'
      - '-240360'
      - '206178'
      - '200'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '6'
      - '0'
      - '0'
    - - '0'
      - '0'
      - '143483'
      - '671073'
      - '0'
      - '-240360'
      - '304592'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '11'
      - '0'
      - '0'
    - - '0'
      - '0'
      - '552800'
      - '561638'
      - '0'
      - '-90646'
      - '304592'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '14'
      - '0'
      - '0'
    - - '0'
      - '0'
      - '1444918'
      - '1030173'
      - '0'
      - '55208'
      - '583258'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '16'
      - '0'
      - '0'
    - - '0'
      - '0'
      - '1650318'
      - '467963'
      - '0'
      - '126006'
      - '327034'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '20'
      - '0'
      - '0'
    - - '0'
      - '0'
      - '1650318'
      - '240119'
      - '0'
      - '271551'
      - '327034'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '24'
      - '0'
      - '0'
    - - '0'
      - '0'
      - '1169405'
      - '441125'
      - '0'
      - '351905'
      - '327034'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '25'
      - '0'
      - '0'
    - - '0'
      - '0'
      - '936947'
      - '902580'
      - '0'
      - '577023'
      - '596299'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '0'
      - '27'
      - '0'
      - '0'
    - - '0'
      - '0'
      - '1608900'
      - '730634'
      - '0'
      - '605659'
      - '596299'
      - '300'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '-2'
      - '35'
      - '0'
      - '0'
    - - '0'
      - '0'
      - '1207626'
      - '1024433'
      - '0'
      - '917362'
      - '658017'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '4'
      - '36'
      - '0'
      - '0'
    - - '0'
      - '0'
      - '1375159'
      - '1023799'
      - '0'
      - '812654'
      - '658017'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '4'
      - '37'
      - '0'
      - '0'
    - - '0'
      - '0'
      - '1690633'
      - '699575'
      - '0'
      - '549500'
      - '658017'
      - '100'
      - '0.3'
      - '0.2'
      - '0'
      - '0'
      - '4'
      - '38'
      - '0'
      - '0'
    - - '0'
      - '0'
      - '1690633'
      - '668184'
      - '0'
      - '549500'
      - '812007'
      - '100'
      - '0.3'
      - '0.2'
      - '1'
      - '15'
      - '0'
      - '-1'
      - '0'
      - '0'
    plan_name: 方案三
